# .github/workflows/ci.yml
name: CI – Lint & Build CSS/JS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ≥20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Lint JavaScript
        run: npx eslint "frontend/js/**/*.js" "public/js/**/*.js"

      - name: Lint CSS
        run: npx stylelint "frontend/css/**/*.css" "public/css/**/*.css"

      - name: Format check
        run: npx prettier --check "**/*.{js,css,php,html}"

      - name: Build Tailwind CSS
        run: npm run build:css
