# .github/workflows/frontend-ci.yml
name: Frontend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: "Code Quality"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 20+
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check JavaScript
        run: |
          if [ -d "frontend/js" ] || [ -d "public/js" ]; then
            echo "Running ESLint on JavaScript files"
            npx eslint "**/*.js" --max-warnings=0
          else
            echo "No JS directories found, skipping ESLint."
          fi
        continue-on-error: true

      - name: Check CSS
        run: |
          if [ -d "frontend/css" ] || [ -d "public/css" ]; then
            echo "Running Stylelint on CSS files"
            npx stylelint "**/*.css"
          else
            echo "No CSS directories found, skipping Stylelint."
          fi
        continue-on-error: true

      - name: Check formatting
        run: npx prettier --check "**/*.{js,css,php,html}"

  build:
    name: "Build Frontend"
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 20+
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Tailwind CSS
        run: npm run build:css

      - name: Save compiled CSS
        uses: actions/upload-artifact@v3
        with:
          name: tailwind-css
          path: public/css/tailwind.css
          
      - name: Verify build output
        run: |
          if [ -f "public/css/tailwind.css" ]; then
            echo "Tailwind CSS built successfully"
          else
            echo "Tailwind CSS build failed"
            exit 1
          fi